### ISSUE TITLE
Dependencies Missing

### ISSUE THREAD

**Issue by ritzdorf** [SeUniVr/EtherSolve#1]
Hi,

I wanted to try the tool, but the installation failed.
I think that there might be some missing dependencies. Can you provide a Dockerfile or add the right dependencies to the gradle settings?

Thanks.

**Comment by VersusF** [comment]
Hello and thanks for trying EtherSolve.

We have developed the tool with IntelliJ, and never used gradle through cli. We're facing some troubles but we're currently working on them. I'll let you know in the next week.

Sorry for that

**Comment by VersusF** [comment]
Hello
I should have fixed the gradle issues (at least in theory :smile:). Checkout the  [branch](https://github.com/SeUniVr/EtherSolve/tree/bugfix/gradle-cli) and tell me if this works also for you, so I can merge it.

The tasks are:
- `runCoreMain`: Run the main class of Core module, which analyses a sample bytecode and produces a JSON output.
- `runIRExtractor`: Run the extractor to get the intermediate representation used for automatic analysis on the paper.
- `jar`: Builds the jar for each module. The main one is the one of the UI module.
- `bootRun`: Launch the tool in a local server. Accessible through `localhost:8081/api`, but it's currently an experimental feature.

The minimum supported gradle version is 5.2.1. In alternative use the wrapper with `./gradlew`.

Please, tell me if this solves your issues.

Filippo

**Comment by ritzdorf** [comment]
Thanks!

Works on Ubuntu with OpenJdk 11, didn't work on ArchLinux, but maybe I messed something up.

Anyway, all good! :+1: 

P.S: Initial quick feedback from trying it: would be great to color the JUMPI edges based on true/false, but obviously it also works like this.

**Comment by VersusF** [comment]
Great! I'll update the README and merge the branch.
Thanks also for the feedback, it could be a nice feature
