### ISSUE TITLE
gradle compile failed

### ISSUE THREAD

**Issue by smartcontract-detect-yzu** [SeUniVr/EtherSolve#2]
Hi,
   I think your paper is grate and i want to try your tool. 
   But it seems  wrong when doing the gradle and something like this happens:
![image](https://user-images.githubusercontent.com/71329338/113379525-58e51c00-93ac-11eb-8722-42c264492f2d.png)

**Comment by VersusF** [comment]
Hello and thanks for tying EtherSolve.

Have you solved your problem? We're facing some troubles when executing gradle on cli (the tool has been developed on IntelliJ), and we're working on it.

Also, which version of gradle are you using? Did you use the gradle wrapper?

Thanks and sorry for the inconvenience

**Comment by smartcontract-detect-yzu** [comment]
hi thanks for your kind reply
and i build the jar like this, and jar is in UI/build/libs：
![image](https://user-images.githubusercontent.com/71329338/113644093-7bca4580-96b6-11eb-906b-0074e34fc13e.png)
